task-2
yumi-kobayashi-17/Household-account-book pull request #2
Opened 2023-03-08 05:14 UTC by yumi-kobayashi-17

## 詳細
* 食費と固定費をデータに持つテーブルを作成
* 日付と費用の種類をプルダウン形式で選択できる機能を追加
* 入力フォーム画面で値を入力し追加ボタンを押すと、テーブルに反映される機能を追加
* (option)テーブルの日付部分を押すと、その日付がプルダウンで選択された状態で入力フォーム画面に遷移する機能を追加
## 画面キャプチャ 
[入力フォーム画面]
<img width="959" alt="image" src="https://user-images.githubusercontent.com/125633908/223624742-26b34fa5-b006-4f47-8f6e-f3eafc3aafc7.png">
[テーブル画面]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/125633908/223624835-93022e7f-b05c-4cfb-adef-33eb66a88b73.png">

2023-03-08 09:54 UTC, cw-takumiohnuki requested changes
面白いぐらい飲み込みがいいので、少し難易度高めな修正依頼出してみました。
やることは、
- データ構造の修正
- Mapへの理解を深める
- 配列関数への理解を深める

そんなこと気にする？ってことかもしれないけど、勉強のために書き直してみてほしい！

2023-03-08 09:54 UTC, soe-ohnuki-takumi-10 commented on src/components/Table.vue
> +            <td><button @click="setDate(dateList.date);setIsActive(1)">{{ dateList.date }}</button></td>
"setDate(dateList.date);setIsActive(1)を一つの関数にして、それを呼び出そう！
基本的に@clickでの処理は一行で書けるものにとどめておきたい。

2023-03-08 09:54 UTC, soe-ohnuki-takumi-10 commented on src/components/HouseholdMain.vue
> +      const setCost = (addedCost: number) => {
## 考え方
一つの関数に対しては可能な限り小さな役割を持たせるように設計してほしいです。
今の関数ではsetCostという関数がfixedCost, foodCostという二つの変数に対する更新をすることになっていて、内部で更新先を切り替えているけれど、このままだと今後更新先が増えた場合、さらに複雑な関数になることが予想されます。

例えば次のタスクで交通費が増えることを考えた場合、このsetCostという関数には
条件分岐（else if）が増えてさらに複雑な関数になってしまいます。
さらに項目が増えるとelse if がどんどん増えていってしまうことになり、
関数の責任がどんどん増大していってしまいます。

このような複雑な条件式を持つ関数は好ましくないです。
なぜならば、このコードを読む人は実務においては他人であることがほとんどで、
初見の人が条件分岐の多いコードを読むことは大変だからです。

ですので、なるべく小さな関数を作って、その関数を結合していくといったイメージで関数は設計したほうが良いコードになりやすいです。


----------------------------------------------------------------------
## ここでの修正案

ここでは条件式ではなく、objectの配列として定義したほうが分岐が少なくなり、わかりやすいコードになるかと思います。

具体的な修正案としては、
```
const cost1 = ref(1)
const cost2 = ref(2)
const cost3 = ref(3)
const setCost1 = (newCost)  => cost1.value=newCost
const setCost2 = (newCost)  => cost2.value=newCost
const setCost3 = (newCost)  => cost3.value=newCost


const items = [{
    target:cost1,
    updater:setCost1
},
{
    target:cost2,
    updater:setCost2
},
{
    target:cost3,
    updater:setCost3
}
]

const setCost = (newCost,targetCost) => items.filter(elm => elm.target === targetCost).updater()

```

※現状の進行速度がとてもよく今後の成長に対する期待しかないので、
少し応用的な目線でも考えてほしくて関数設計における考え方についてコメントしました。
今すぐには理解できなくても、いつかきっと役立つと思うのでそういう考え方もあるんだーくらいで記憶の片隅に置いておいてもらえると嬉しいです。
「保守性」、「拡張性」って観点はぜひ持ちながらタスクを行ってもらいたいなーと思います。

2023-03-08 09:54 UTC, cw-takumiohnuki commented on src/components/Table.vue
> +            <td><button @click="setDate(dateList.date);setIsActive(1)">{{ dateList.date }}</button></td>
jsでの複雑な処理（＝一行以上の処理）はscript内で書いてほしい
templateはあくまでHTMLを定義する場所なので。

2023-03-08 09:54 UTC, cw-takumiohnuki commented on src/components/HouseholdMain.vue
> +      const selectCostType = ref<string>('foodCost');
idと名称で管理したほうが奇麗かも！
```
const costTypes = [
{id: 1, item: foodCost},
{id:2, item:fixedCost}
]
const selectType = ref<number>(1)
```
selectTypeはid:numberで管理して、使うときは、
`selectType.find(elm => elm.id === selectType.value) ?? ''`として使う

2023-03-08 09:54 UTC, cw-takumiohnuki commented on src/components/HouseholdMain.vue
> +      const foodCosts = ref(Array(30));
現状であれば、これで全く問題ないと思う！

ただ、例えば次のタスクで、5月についてのテーブルを追加したいとなったら、どうだろうか？
またfoodConstsとfixedCostsの定義を別々に持たせないといけなくなるよね？
意味のまとまりごとにデータは定義すべきであると考えると、
ここでのデータ構造は、
月一つに対して、日、曜日、値のまとまりが複数と捉えることができると思う。
```
[
{
    month:4,
    item:
        [
            {
                day:1,
                date:"月",
                cost:{
                    fixed:100,
                    food:200
                }
            },
            {
                day:2,
                date:"火",
                cost:{
                    fixed:200,
                    food:300
                }
            }
        ]
},
{
    month:5,
    item:
        [
            {
                day:1,
                date:"月",
                cost:{
                    fixed:100,
                    food:200
                }
            },
            {
                day:2,
                date:"火",
                cost:{
                    fixed:200,
                    food:300
                }
            }
        ]
},
]
```

2023-03-08 09:54 UTC, cw-takumiohnuki commented on src/components/Table.vue
> +        for (let i = 0; i < dateLists.length; i++) {
ここでやっていることは大正解！
実装としても問題ないです。

ただ、今回は勉強として可能な限り、
if, for はそれぞれ三項演算子、配列関数を使った書き方で書いてほしいです。
三項演算子を使う理由はコードが簡潔になるからだけなのですが、
配列関数は特に意識してほしい点です。
配列関数は使うことが多いし、しかも使い方が慣れるまで難しいからこの段階から慣れてほしいです。

ここ少し難しいですが、3行程度で同様の処理が書けます。
処理の中身を自分で追ってみながら
できれば、ここへの返信で下記の処理が何をしているか自分で説明してみてほしいです。
```
const dates: number[] = [...Array(30)].map((_, i) => i + 1);
const days = new Map([[1,'土'],[2,'日'],[3,'月'],[4,'火'],[5,'水'],[6,'木'],[7,'金']])
const list = dates.map((date,index) => ({date,day:days.get(index%7)??''})
```

2023-03-08 09:54 UTC, soe-ohnuki-takumi-10 commented on src/components/Table.vue
> +        for (let i = 0; i < dateLists.length; i++) {
参考までに、
- Map
　- https://jsprimer.net/basic/map-and-set/

Mapと配列関数のmapは別物なので注意！

2023-03-08 09:54 UTC, cw-takumiohnuki commented on src/components/Form.vue
> +          @click="
@click内の処理を一つの関数にして、それを呼び出そう！
基本的に@clickでの処理は一行で書けるものにとどめておきたい。

2023-03-08 09:54 UTC, soe-ohnuki-takumi-10 commented on src/components/HouseholdMain.vue
> +      const foodCosts = ref(Array(30));
こんな感じのデータ構造になるようにfoodCosts, foxedCosts, dateを書き直してみよう！

2023-03-08 09:54 UTC, cw-takumiohnuki commented on src/components/Form.vue
> +      const selectDate2 = ref(props.selectDate);
propsとして受け取った値を初期値として持たせる構造とても良い！
ただ、命名だけ気にしてほしいです。

`currentDate`とかかな？

2023-03-08 09:54 UTC, cw-takumiohnuki commented on src/components/Form.vue
> +      const cost2 = ref(props.cost);
同上

2023-03-08 09:54 UTC, cw-takumiohnuki commented on src/components/Form.vue
> +      const selectCostType2 = ref(props.selectCostType);
同上

2023-03-08 09:54 UTC, cw-takumiohnuki commented on src/components/Form.vue
> +        <option :value="date" v-for="date in 30">{{ date }}</option>
30回繰り返すって書き方としてはいいと思う！
ただ、30ではなく4月が持つ日数分繰り返すように書いたほうがいいかも！

理由は、30をべた書きにしてしまうとバグの原因になりうるからです。

2023-03-10 02:39 UTC, yumi-kobayashi-17 commented on src/components/Table.vue
> +        for (let i = 0; i < dateLists.length; i++) {
- [1,2,...30]の配列を用意
- 7で割った余りがキー、対応する曜日が値となる連想配列を用意（（[0, '土'], [1, '日']...[6, '金']）でしょうか？）
- date,dayを要素に持つ配列listを作成。dateは配列datesをmap関数によって順番に取り出し、dayは（日にちー１）の値を７で割った余りをキーに持つ値を配列daysから取り出している。

このような流れでしょうか？
２行目をそのまま実行すると金曜日が表示されなくなるので変更してみました。

2023-03-10 08:03 UTC, takumi-13 requested changes
大筋はよくできているかと思います！
少し細かい部分について追加指摘＆classの当て方についてコメントしたので、やってみてー！

2023-03-10 08:03 UTC, takumi-13 commented on src/components/Form.vue
> +      dateList: {
これ、type: Arrayかな
また、関数のように、Array as PropType<型>のように書いてあげた方がいいかも！

2023-03-10 08:03 UTC, takumi-13 commented on src/components/Form.vue
> +        type: Object,
ここも、Objectだけだと、どんなObjectか？って部分の型チェックが働かないので、
Object as PropType<型>って書いてあげた方が安全かも！

2023-03-10 08:03 UTC, takumi-13 commented on src/components/Form.vue
> +        <option :value="costTypes[0].id">食費</option>
食費とidの配列作って、それをv-forで回して表示するようにできるといいかなー

2023-03-10 08:03 UTC, takumi-13 commented on src/components/Form.vue
> +          @click="props.setPayment(currentDate, currentCostType, currentCost)"
適切に関数化できていてGood!!

2023-03-10 08:03 UTC, takumi-13 commented on src/components/Form.vue
> +        <option :value="costTypes[0].id">食費</option>
costTypesあるので、それを基にv-for使えばいいかなー

2023-03-10 08:03 UTC, takumi-13 commented on src/components/HouseholdMain.vue
> +      const paymentsData: paymentsDataType[] = dateList.map((elm) => ({
optionについてのコメント
下の方で書いていたtableClassもここで一緒に定義してあげるとどうだろう？

computed使うって言ったけど、必要なさそうかもしれない。。。
適当なこと言って本当にごめんなさい。。。

参考までに、computedって何？について説明しておくと、
computedは算出プロパティと呼ばれるもので、
その名の通り、内部のデータに変化があった際に自動で再計算を中に書かれている計算を自動で行ってデータを書き換えてくれるものです。

例えば、
```
const x = ref(1)
const y = computed (() => {
 x.value+1
})
```
のようなコードがあったとして、
どこかでxの値に変化があって、x.value=10になった場合、
何もしなくてもy=11と再計算してくれます。

今回はtableClassの判定に使うdateは固定値であるため、computed使わなくても大丈夫そうですね。

2023-03-10 08:03 UTC, takumi-13 commented on src/components/HouseholdMain.vue
> +      const paymentsData: paymentsDataType[] = dateList.map((elm) => ({
tableClass: getClass(elm.date)として、パラメータ持たせてあげて、

const getClass= (date: string):string => {
判定用の関数
}
getClassの最終的な返り値としては、'bg-red-200 font-xl'のような空白で区切られた文字列の方が後々楽そうかなー

保守性とか考えると、一度string[]として、const x = ['bg-red-200','font-xl']みたいに定義してから、それをstringに変換して, ','を' 'にする処理実行すればよさそう

2023-03-10 08:03 UTC, takumi-13 commented on src/components/Table.vue
> +          <tr v-for="d in dateList" class="border-2">
classを適用する都合上行ごとにv-for回した方がいいかも
こんなかんじかなー？
```
// 一行目
 <th>
   <td>
　　//ヘッダーの4列分の要素（日付、曜日、食費、固定費）
   </td>
 </th>
 <tr　v-for="30日分" :class="tableCalss">
   <td>
     // ４列分の要素（それぞれの値）
   </td>
 </tr>
// 
```

2023-03-10 08:03 UTC, takumi-13 commented on src/components/Form.vue
> +        type: Object,
少し紛らわしいんだけど、
Array,Objectはvueのプロップで渡すうえでの宣言みたいなもので、配列ですよーでもその中身はよくわからないけどねーって状態なのね。
詳細を定義するためには、PropTypeを使わないといけなくて、そうしないと、例えば本当はstring[]に限定したいのにnumber[]でも渡せてしまったりするので、それを防ぐためにもPropTypeで中身の型情報まで書いてあげた方がよかったりする。

2023-03-13 01:11 UTC, yumi-kobayashi-17 commented on src/components/HouseholdMain.vue
> +      const paymentsData: paymentsDataType[] = dateList.map((elm) => ({
getClass関数を作ると、中身の条件分岐が7個になる書き方しか思いつかず、新しくtableColorClass配列を作ってmap関数を使ってdateListに挿入してみました。
提案していただいた書き方と違うので、もし不適切だったら教えてください！

2023-03-13 02:47 UTC, cw-takumiohnuki requested changes
条件分岐増えすぎることを嫌うという考え方できているの、とっても素晴らしい！！！
Map二つ用意しているのがやや冗長に感じたので、修正案書いてみましたー
確認お願いします！

- typeが増えてきたので、別ファイルへの書き出し。
- Mapを二つ使っていて、それらが同じkey値を参照しているので、一つのObjectへの統合。

2023-03-13 02:47 UTC, cw-takumiohnuki commented on src/components/HouseholdMain.vue
> +  export type DateList = {
type増えてきたので、DateList , CostTypes, PaymentsDataType を外部ファイルで(src/types/util.tsとか作って)定義するように移動してみようか！

2023-03-13 02:47 UTC, cw-takumiohnuki commented on src/components/HouseholdMain.vue
> +  export type CostTypes = {
ちょっと細かいけど、
type CostType = {
  id: number;
  item: string;  
}
と定義してから、type CostTypeList = CostType[]とかのほうが見やすいかなー

2023-03-13 02:47 UTC, cw-takumiohnuki commented on src/components/HouseholdMain.vue
> +      const paymentsData: paymentsDataType[] = dateList.map((elm) => ({
条件分岐増える書き方を嫌うていう考え方出来ているの素晴らしいね！！
そうだね、単純に条件分岐で書こうとすると煩雑になるねー
Map使おうとすることもとても素晴らしいと思う！

ただ、今回だともう一つ上にdaysがあって、keyとなる0,1,2...が同じ意味合いで使えるのね。
この場合だと一つのObjectとしてまとめたほうが見通しが良くなるかなー

`元々`
```
const days = new Map([
        [0, '土'],
        [1, '日'],
        [2, '月'],
        [3, '火'],
        [4, '水'],
        [5, '木'],
        [6, '金'],
      ]);
const tableColorClass = new Map([
        [0, 'bg-red-100'],
        [1, 'bg-orange-100'],
        [2, 'bg-yellow-100'],
        [3, 'bg-green-100'],
        [4, 'bg-sky-100'],
        [5, 'bg-purple-100'],
        [6, 'bg-rose-100'],
      ]);
```

`修正案`
const days = [
{
 id: 0,
 day: '土',
 style: 'bg-red-100'
},
{ 
 id:1,
 day:'日',
 style:'bg-orange-100'
}
...
]

さらにこの場合、今まで
days.getや、tableColorClass.get使っていた箇所がMapオブジェクト使ってないから`get`が使えなくなるので、
`find`か`filter`使った実装に切り替わることになると思う。
find, filterの使い方は下記を参照しながら使ってみてほしい！
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/find
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

2023-03-13 07:09 UTC, cw-takumiohnuki approved these changes
findも上手に使えていていいと思います！
その調子で次も頑張ろう！！！

2023-03-13 07:09 UTC, cw-takumiohnuki commented on src/components/HouseholdMain.vue
> +        day: days.find((elm) => elm.id === index % 7)?.day,
おー！よく使えてる！！
めっちゃ簡潔に書かれていて奇麗なコードになってる！

ただのコメントだけど、
`find`と`filter`の使い分けとしては、検索条件に一致した値が複数あった場合の処理に違いがあります
例えば、
```
const list = ["a","b","c","d","a"]

// 実行結果は"a"
const resFindCorrect = list.find(elm => elm === "a")
// 実行結果は["a","a"]
const resFilterCorrect = list.filter(elm => elm === "a")
// [0]つけてあげれば、findと同じ実行結果になり、実行結果は"a"
const resFilterCorrect = list.filter(elm => elm === "a")[0]

// find使って検索条件に一致する値がなかった場合は実行結果はundefined
const resFindError = list.find(elm => elm === "z")
// filter使って検索条件に一致する値がなかった場合は実行結果は[]
const resFilterError = list.filter(elm => elm === "z")
```
なので、一つだけほしい場合はfilter使って結果[0]としてもいいし、find使ってもいいということになります。
filterも配列のまま次の処理に使いたい場合よく使うので併せて押さえておくといいかな！

※`day: days.find((elm) => elm.id === index % 7)?.day`にある`?.`はオプションナルチェーンと言ってfindの実行結果が`undefined`だった場合エラーではなく`undefined`を返却するための機能です。

2023-03-13 07:09 UTC, cw-takumiohnuki commented on src/components/HouseholdMain.vue
> +      const days: Days[] = [
Objectとしてまとめて定義されていて見通しが良くなっている！

2023-03-13 07:10 UTC, merged

2023-03-13 07:20 UTC, yumi-kobayashi-17 commented on src/components/HouseholdMain.vue
> +        day: days.find((elm) => elm.id === index % 7)?.day,
`?.` は勝手に補完されるので不思議に思っていたところでした、、笑
補足説明ありがとうございます！